# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-my-app
  namespace: argocd
spec:
  description: Frontend project
  sourceRepos:
    - https://github.com/aorko16/Helm-Argocd-01.git
  destinations:
    - namespace: my-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd      
spec:
  project: frontend-my-app     # match project name 
  source:
    repoURL: https://github.com/aorko16/Helm-Argocd-01.git
    targetRevision: main
    path: my-app
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # auto namespace
      - PrunePropagationPolicy=foreground   # child resource delete then parent
      - PruneLast=true   # create new resource , old delete
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m     # 3 minutes
