sonar.projectKey=aorko16_Helm-Argocd-multi-env-03
sonar.organization=bangla-project
sonar.projectName=Helm-Argocd-multi-env-03
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.xml,**/Dockerfile
sonar.language=web


