sonar.projectKey=aorko16_Helm-Argocd-multi-env-03  ← FIXED ❌ don't change
sonar.organization=aorko16                          ← FIXED ❌ don't change
sonar.projectName=whatever you want                 ← FREE ✅ change freely
sonar.sources=bangla                                ← match your folder name
sonar.language=web                                  ← keep for HTML
